os: linux
sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install coveralls

script:
  - make test

after_success:
  - coveralls
  
notifications:
  email: false
